# Site settings
title: "nahuelhds ğŸ‘¨â€ğŸ’»"
description: "My technical blog"
email: "nahuelhds@gmail.com"

baseurl: ""
url: "https://nahuelhds.dev"

twitter_username: "nahuelhds"
github_username: "nahuelhds"
instagram_username: "programming.geek"
facebook_username: "nahuelhds"

timezone: "America/Montevideo"

# Build settings
markdown: "kramdown"
kramdown:
  input: "GFM"

include:
  - "_img"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Nahuel Sotelo"
